apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/enterprise-contract/ec-cli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ec-main-ci
    appstudio.openshift.io/component: cli-main-ci
    pipelines.appstudio.openshift.io/type: build
  name: cli-main-ci-on-pull-request
  namespace: rhtap-contract-tenant
spec:
  params:
    - name: dockerfile
      value: Dockerfile.dist
    - name: git-url
      value: '{{source_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci:on-pr-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: prefetch-input
      value: gomod
    - name: build-source-image
      value: "true"
    - name: build-args-file
      value: quick-build-args.conf
  pipelineSpec:
    finally:
      - name: show-sbom
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
        taskRef:
          params:
            - name: name
              value: show-sbom
            - name: bundle
              value: quay.io/lucarval/task-show-sbom:0.1@sha256:16e6c780e1fd9708ad905a01a423798a4f80490a1f1f8d47ea0a86eefe29592f
            - name: kind
              value: task
          resolver: bundles
      - name: show-summary
        params:
          - name: pipelinerun-name
            value: $(context.pipelineRun.name)
          - name: git-url
            value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
          - name: image-url
            value: $(params.output-image)
          - name: build-task-status
            value: $(tasks.build-container.status)
        taskRef:
          params:
            - name: name
              value: summary
            - name: bundle
              value: quay.io/lucarval/task-summary:0.2@sha256:bf5b44763dbc3946e0195c6192bc5230834a1f5d25faea26e156bdb321e03668
            - name: kind
              value: task
          resolver: bundles
        workspaces:
          - name: workspace
            workspace: workspace
    params:
      - description: Source Repository URL
        name: git-url
        type: string
      - default: ""
        description: Revision of the Source Repository
        name: revision
        type: string
      - description: Fully Qualified Output Image
        name: output-image
        type: string
      - default: .
        description: Path to the source code of an application's component from where to build image.
        name: path-context
        type: string
      - default: Dockerfile
        description: Path to the Dockerfile inside the context specified by parameter path-context
        name: dockerfile
        type: string
      - default: "false"
        description: Force rebuild image
        name: rebuild
        type: string
      - default: "false"
        description: Skip checks against built image
        name: skip-checks
        type: string
      - default: "false"
        description: Execute the build with network isolation
        name: hermetic
        type: string
      - default: ""
        description: Build dependencies to be prefetched by Cachi2
        name: prefetch-input
        type: string
      - default: "false"
        description: Java build
        name: java
        type: string
      - default: ""
        description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
        name: image-expires-after
      - default: "false"
        description: Build a source image.
        name: build-source-image
        type: string
      - default: ""
        description: Path to a file with build arguments which will be passed to podman during build
        name: build-args-file
        type: string
    results:
      - description: ""
        name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - description: ""
        name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
      - description: ""
        name: CHAINS-GIT_URL
        value: $(tasks.clone-repository.results.url)
      - description: ""
        name: CHAINS-GIT_COMMIT
        value: $(tasks.clone-repository.results.commit)
      - description: ""
        name: JAVA_COMMUNITY_DEPENDENCIES
        value: $(tasks.build-container.results.JAVA_COMMUNITY_DEPENDENCIES)
    tasks:
      - name: init
        params:
          - name: image-url
            value: $(params.output-image)
          - name: rebuild
            value: $(params.rebuild)
          - name: skip-checks
            value: $(params.skip-checks)
        taskRef:
          params:
            - name: name
              value: init
            - name: bundle
              value: quay.io/lucarval/task-init:0.2@sha256:722f09163c7d69eaebee0b43f59fe8540967180158d2782cbf739956a4d7d825
            - name: kind
              value: task
          resolver: bundles
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
          - name: ociStorage
            value: $(params.output-image).git
          - name: ociArtifactExpiresAfter
            value: $(params.image-expires-after)
          - name: depth
            value: "0"
          - name: fetchTags
            value: "true"
        runAfter:
          - init
        taskRef:
          params:
            - name: name
              value: git-clone-oci-ta
            - name: bundle
              value: quay.io/lucarval/task-git-clone-oci-ta:0.1@sha256:052cef641db5fc7668fb539ab7560ac431e7ae8eef9286b606ccc5547353f566
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
        workspaces:
          - name: basic-auth
            workspace: git-auth
      - name: prefetch-dependencies
        params:
          - name: input
            value: $(params.prefetch-input)
          - name: source-artifact
            value: $(tasks.clone-repository.results.sourceArtifact)
          - name: oci-storage
            value: $(params.output-image).prefetch
          - name: oci-artifact-expires-after
            value: $(params.image-expires-after)
        runAfter:
          - clone-repository
        taskRef:
          params:
            - name: name
              value: prefetch-dependencies-oci-ta
            - name: bundle
              value: quay.io/lucarval/task-prefetch-dependencies-oci-ta:0.1@sha256:3250fc9eb81a6e56c32a8d9089793b1076f99b753c56bf0af088e0b91db850cf
            - name: kind
              value: task
          resolver: bundles
        workspaces:
          - name: git-basic-auth
            workspace: git-auth
      - name: build-container
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: HERMETIC
            value: $(params.hermetic)
          - name: PREFETCH_INPUT
            value: $(params.prefetch-input)
          - name: IMAGE_EXPIRES_AFTER
            value: $(params.image-expires-after)
          - name: COMMIT_SHA
            value: $(tasks.clone-repository.results.commit)
          - name: BUILD_ARGS_FILE
            value: $(params.build-args-file)
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.source-artifact)
          - name: CACHI2_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.cachi2-artifact)
        runAfter:
          - prefetch-dependencies
        taskRef:
          params:
            - name: name
              value: buildah-oci-ta
            - name: bundle
              value: quay.io/lucarval/task-buildah-oci-ta:0.1@sha256:75bd92eacd8367ca954d65ee49dc3b0cff2a1d96f083e58cc1d6a2b84559746a
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
      - name: build-source-image
        params:
          - name: BINARY_IMAGE
            value: $(params.output-image)
          - name: BASE_IMAGES
            value: $(tasks.build-container.results.BASE_IMAGES_DIGESTS)
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.source-artifact)
          - name: CACHI2_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.cachi2-artifact)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: source-build-oci-ta
            - name: bundle
              value: quay.io/lucarval/task-source-build-oci-ta:0.1@sha256:1c6cc32c2459eca0f3a63eef9f2efc7ef13e68c17d702c19324df428f54fa154
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(tasks.init.results.build)
            operator: in
            values:
              - "true"
          - input: $(params.build-source-image)
            operator: in
            values:
              - "true"
      - name: deprecated-base-image-check
        params:
          - name: BASE_IMAGES_DIGESTS
            value: $(tasks.build-container.results.BASE_IMAGES_DIGESTS)
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: deprecated-image-check
            - name: bundle
              value: quay.io/lucarval/task-deprecated-image-check:0.4@sha256:7ddf832ab8976b2bb721cfd78c488ff123b90a644f56dbbfcda4ddf71e68086a
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: clair-scan
        params:
          - name: image-digest
            value: $(tasks.build-container.results.IMAGE_DIGEST)
          - name: image-url
            value: $(tasks.build-container.results.IMAGE_URL)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: clair-scan
            - name: bundle
              value: quay.io/lucarval/task-clair-scan:0.1@sha256:924b9831c7543e629fa926be73c5b67840538068e8cd9209c035beb95550c450
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: ecosystem-cert-preflight-checks
        params:
          - name: image-url
            value: $(tasks.build-container.results.IMAGE_URL)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: ecosystem-cert-preflight-checks
            - name: bundle
              value: quay.io/lucarval/task-ecosystem-cert-preflight-checks:0.1@sha256:3f69baf08fc9fdc9e905c9c74ee68fa5c5c29844a253cbdde4b08fd723426e09
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: sast-snyk-check
        params:
          - name: SOURCE_ARTIFACT
            value: $(tasks.prefetch-dependencies.results.source-artifact)
        runAfter:
          - clone-repository
        taskRef:
          params:
            - name: name
              value: sast-snyk-check-oci-ta
            - name: bundle
              value: quay.io/lucarval/task-sast-snyk-check-oci-ta:0.1@sha256:efd5cc2651a911dd0dd57e9ab6cef985444b17c62cbaab2ded6fe905167fc740
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: clamav-scan
        params:
          - name: image-digest
            value: $(tasks.build-container.results.IMAGE_DIGEST)
          - name: image-url
            value: $(tasks.build-container.results.IMAGE_URL)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: clamav-scan
            - name: bundle
              value: quay.io/lucarval/task-clamav-scan:0.1@sha256:4d5cdccd559cda271fc2d4de22eb599fdbb47b11be578cb7161dcc955eb67afd
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: sbom-json-check
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: sbom-json-check
            - name: bundle
              value: quay.io/lucarval/task-sbom-json-check:0.1@sha256:7d3e982ce09e9000f6e1d2ec7998ef881dc77698a0a58f0c4c88aa1761118eda
            - name: kind
              value: task
          resolver: bundles
        when:
          - input: $(params.skip-checks)
            operator: in
            values:
              - "false"
      - name: apply-tags
        params:
          - name: IMAGE
            value: $(tasks.build-container.results.IMAGE_URL)
        runAfter:
          - build-container
        taskRef:
          params:
            - name: name
              value: apply-tags
            - name: bundle
              value: quay.io/lucarval/task-apply-tags:0.1@sha256:3b8193fa8947fb4124d4a4cb5740abd43458f2ec0ec12faee6a1cdc59cf96e23
            - name: kind
              value: task
          resolver: bundles
    workspaces:
      - name: workspace
      - name: git-auth
        optional: true
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
