apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    appstudio.openshift.io/application: ec-release-debugging
    appstudio.openshift.io/component: verify-enterprise-contract-task
    pipelines.appstudio.openshift.io/type: build
  name: verify-enterprise-contract-task-on-pull-request
  namespace: rhtap-contract-tenant
spec:
  params:
  - name: dockerfile
    value: docker/Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/jstuart/verify-enterprise-contract-task:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineSpec:
    finally:
    - name: show-sbom
      params:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      taskRef:
        params:
        - name: name
          value: show-sbom
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-show-sbom:0.1@sha256:82737c8d365c620295fa526d21a481d4614f657800175ddc0ccd7846c54207f8
        - name: kind
          value: task
        resolver: bundles
    - name: show-summary
      params:
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: git-url
          value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
        - name: image-url
          value: $(params.output-image)
        - name: build-task-status
          value: $(tasks.build-container.status)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: summary
          - name: bundle
            value: quay.io/jstuart/task-summary:0.1@sha256:4e336716b68ef00a433c0def84766b1ca25a8c5fb769503d2c09d33072a38f4c
          - name: kind
            value: task
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: .
      description: Path to the source code of an application's component from where to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Java build
      name: java
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
    - default: "false"
      description: Build a source image.
      name: build-source-image
      type: string
  results:
    - name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/jstuart/task-init:0.2@sha256:765d527b933a922f5a7b529c152415212744fff242bd5488cc77ecec3873237a
          - name: kind
            value: task
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone
          - name: bundle
            value: quay.io/jstuart/task-git-clone:0.1@sha256:20e63015813aa7cf3a3d5253f4f3173202f000b95727fe4bebff21ab63a5075b
          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)
      runAfter:
        - clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies
          - name: bundle
            value: quay.io/jstuart/task-prefetch-dependencies:0.1@sha256:c8659aba6fa551421f9617ae7ff0d753af26d284c00847c8a5df6b08bb610204
          - name: kind
            value: task
      when:
        - input: $(params.hermetic)
          operator: in
          values:
            - "true"
      workspaces:
        - name: source
          workspace: workspace
    - name: build-container
      params:
      - name: IMAGE
        value: quay.io/jstuart/verify-enterprise-contract-task:pr-{{revision}}
      - name: CONTEXT 
        value: ./source/tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
      - name: HOME 
        value: /tekton/tekton-home
      runAfter:
        - prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: tkn-bundle
          - name: bundle
            value: quay.io/jstuart/task-tkn-bundle:0.1@sha256:b81ba55d5402ef4f97be31d557fcbb5c4183f0abeca4be415dc173c9634ef7c5
          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
      - name: source
        workspace: workspace
      - name: registry-auth
        workspace: registry-auth
    # - name: build-source-image
    #   params:
    #   - name: BINARY_IMAGE
    #     value: $(params.output-image)
    #   - name: BASE_IMAGES
    #     value: $(tasks.build-container.results.BASE_IMAGES_DIGESTS)
    #   runAfter:
    #   - build-container
    #   taskRef:
    #     params:
    #     - name: name
    #       value: source-build
    #     - name: bundle
    #       value: quay.io/redhat-appstudio-tekton-catalog/task-source-build:0.1@sha256:3ad20adff4aa5cd153695b115133cb7c71c87f095af02fae5932396b1c72eb00
    #     - name: kind
    #       value: task
    #     resolver: bundles
    #   when:
    #   - input: $(tasks.init.results.build)
    #     operator: in
    #     values:
    #     - "true"
    #   - input: $(params.build-source-image)
    #     operator: in
    #     values:
    #     - "true"
    #   workspaces:
    #   - name: workspace
    #     workspace: workspace
    # - name: deprecated-base-image-check
    #   params:
    #   - name: BASE_IMAGES_DIGESTS
    #     value: $(tasks.build-container.results.BASE_IMAGES_DIGESTS)
    #   runAfter:
    #   - build-container
    #   taskRef:
    #     params:
    #     - name: name
    #       value: deprecated-image-check
    #     - name: bundle
    #       value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.3@sha256:a299ff57d97f3924020634625dfb9bbc66547124ca23a3396e338c645f7b4a8e
    #     - name: kind
    #       value: task
    #     resolver: bundles
    #   when:
    #   - input: $(params.skip-checks)
    #     operator: in
    #     values:
    #     - "false"
    - name: clair-scan
      params:
        - name: image-digest
          value: $(tasks.build-container.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
        - build-container
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan
          - name: bundle
            value: quay.io/jstuart/task-clair-scan:0.1@sha256:a2341bb7f7163cf416c8893726764c467c5c8ead8be3b8b71e321ffca89bf808
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: sast-snyk-check
      runAfter:
        - clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check
          - name: bundle
            value: quay.io/jstuart/task-sast-snyk-check:0.1@sha256:b9e7504eb93287e688cad678ef04a7f163237e10f81b42be47d4bf3a26f47e88
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
      workspaces:
        - name: workspace
          workspace: workspace
    - name: clamav-scan
      params:
        - name: image-digest
          value: $(tasks.build-container.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-container.results.IMAGE_URL)
      runAfter:
        - build-container
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan
          - name: bundle
            value: quay.io/jstuart/task-clamav-scan:0.1@sha256:eb788b203902b056a0e41e126b3850aab6ce898fd3a7fefc0ccce7e5e0495b5b
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
  workspaces:
    - name: workspace
    - name: git-auth
      optional: true
    - name: registry-auth
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: registry-auth
    secret:
      secretName: quay-release-engineering
status: {}
